eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
okta:
  oauth2:
    issuer: https://dev-60993184.okta.com/oauth2/default
    audience: api://default
